"""relationship methods

Revision ID: 0a4b47880cd5
Revises: 86a9c10c0fd3
Create Date: 2024-01-09 01:07:22.735938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4b47880cd5'
down_revision = '86a9c10c0fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
