"""many to many relationship

Revision ID: 27b70712a4e5
Revises: 1ae7c90ccc17
Create Date: 2024-01-09 00:30:56.888145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b70712a4e5'
down_revision = '1ae7c90ccc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
