"""many to many relationship

Revision ID: 86a9c10c0fd3
Revises: 27b70712a4e5
Create Date: 2024-01-09 00:58:20.074738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a9c10c0fd3'
down_revision = '27b70712a4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
